### ISSUE TITLE
Create working pdf rendering example

### ISSUE THREAD

**Issue by BeckmaR** [BeckmaR/EmbeddedMultimediaSS2016#1]
The example should be able to do the following:
- Show pages of a pdf file
- Show one specific page of a pdf file
- Use some basic qt GUI widget-whateveridoo to display pdf page in
- Display pdf page fullscreen

In the end, a decision should be made if pdf rendering or a stack of images is used to show the presentation.

**Comment by timheb** [comment]
Done
